const canvas = document.querySelector('#game');
const c = canvas.getContext('2d');
const ui = Object.fromEntries(['score','wave','best','healthBar','healthNum','energyBar','ammoNum','weaponName','combo','objectiveText','finalScore','finalWave'].map(id=>[id,document.getElementById(id)]));
const screens={start:document.getElementById('startScreen'),pause:document.getElementById('pauseScreen'),over:document.getElementById('gameOverScreen')};
let W,H,dpr,game,raf,last=0,mouse={x:0,y:0,down:false},keys={};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), rand=(a,b)=>a+Math.random()*(b-a), dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;c.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
function reset(){game={active:true,paused:false,time:0,score:0,wave:1,spawn:0,enemies:[],bullets:[],particles:[],pickups:[],stars:Array.from({length:115},()=>({x:Math.random()*W,y:Math.random()*H,z:rand(.2,1)})),player:{x:W/2,y:H/2,r:16,angle:0,hp:100,energy:100,fire:0,dash:0,inv:0,combo:1,kills:0,weapon:0},shake:0}; waveStart(); updateUI()}
function waveStart(){const g=game;g.remaining=5+g.wave*3;g.spawn=1.2;ui.objectiveText.textContent=`WAVE ${String(g.wave).padStart(2,'0')} // HOSTILES INBOUND`}
function start(){screens.start.classList.add('hidden');screens.over.classList.add('hidden');reset();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function spawnEnemy(){let side=Math.floor(Math.random()*4), x,y; if(side===0){x=-40;y=Math.random()*H}else if(side===1){x=W+40;y=Math.random()*H}else if(side===2){x=Math.random()*W;y=-40}else{x=Math.random()*W;y=H+40}; let elite=Math.random()<Math.min(.08+game.wave*.018,.32);game.enemies.push({x,y,r:elite?21:14,hp:elite?4+game.wave:1+Math.floor(game.wave/4),max:elite?4+game.wave:1+Math.floor(game.wave/4),speed:(elite?62:88)+game.wave*4,elite,hit:0,angle:0})}
function burst(x,y,color,count=12){for(let i=0;i<count;i++)game.particles.push({x,y,vx:Math.cos(rand(0,6.28))*rand(25,190),vy:Math.sin(rand(0,6.28))*rand(25,190),life:rand(.25,.65),max:.65,size:rand(1,4),color})}
function shoot(){let p=game.player;if(p.fire>0||p.energy<6)return;p.fire=p.weapon?0.09:.16;p.energy-=p.weapon?10:6;let spread=p.weapon ? .12 : .035;for(let i=0;i<(p.weapon?3:1);i++){let a=p.angle+rand(-spread,spread);game.bullets.push({x:p.x+Math.cos(a)*20,y:p.y+Math.sin(a)*20,vx:Math.cos(a)*760,vy:Math.sin(a)*760,life:.85,r:p.weapon?4:3,damage:p.weapon?2:1,color:p.weapon?'#ff5b9a':'#61f7ff'})} burst(p.x+Math.cos(p.angle)*20,p.y+Math.sin(p.angle)*20,p.weapon?'#ff5b9a':'#61f7ff',4)}
function hitEnemy(e,b){e.hp-=b.damage;e.hit=.11;burst(b.x,b.y,b.color,4);if(e.hp<=0){game.score+=e.elite?250:100;game.player.kills++;game.player.combo=Math.min(9,1+Math.floor(game.player.kills/5));burst(e.x,e.y,e.elite?'#ffca61':'#ff3b81',e.elite?28:15);if(Math.random()<.15)game.pickups.push({x:e.x,y:e.y,r:10,type:Math.random()<.52?'heal':'weapon',life:8});return true}return false}
function update(dt){let g=game,p=g.player;g.time+=dt;g.shake=Math.max(0,g.shake-dt*26);p.fire-=dt;p.dash-=dt;p.inv-=dt;p.energy=clamp(p.energy+dt*16,0,100);let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dy=(keys.KeyS?1:0)-(keys.KeyW?1:0);let mag=Math.hypot(dx,dy)||1, speed=p.dash>0?670:250;p.x=clamp(p.x+dx/mag*speed*dt,18,W-18);p.y=clamp(p.y+dy/mag*speed*dt,18,H-18);p.angle=Math.atan2(mouse.y-p.y,mouse.x-p.x);if(mouse.down)shoot();
g.spawn-=dt;if(g.remaining>0&&g.spawn<=0){spawnEnemy();g.remaining--;g.spawn=clamp(.78-g.wave*.018,.28,.78)}if(g.remaining===0&&g.enemies.length===0){g.wave++;waveStart()}
for(let b of g.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}g.bullets=g.bullets.filter(b=>b.life>0&&b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);
for(let e of g.enemies){let a=Math.atan2(p.y-e.y,p.x-e.x);e.angle=a;e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;e.hit-=dt;if(dist(e,p)<e.r+p.r){if(p.inv<=0){p.hp-=e.elite?18:9;p.inv=.55;g.shake=12;burst(p.x,p.y,'#ff3b81',13);if(p.hp<=0){end();return}}e.x-=Math.cos(a)*20;e.y-=Math.sin(a)*20}}
for(let i=g.bullets.length-1;i>=0;i--){let b=g.bullets[i], hit=g.enemies.find(e=>dist(e,b)<e.r+b.r);if(hit){g.bullets.splice(i,1);let dead=hitEnemy(hit,b);if(dead)g.enemies.splice(g.enemies.indexOf(hit),1)}}
for(let q of g.pickups){q.life-=dt;if(dist(q,p)<q.r+p.r+8){if(q.type==='heal')p.hp=clamp(p.hp+28,0,100);else{p.weapon=1;setTimeout(()=>{if(game&&game.player===p)p.weapon=0},7000)}q.life=0;burst(q.x,q.y,q.type==='heal'?'#53ff9f':'#ff5b9a',18)}}g.pickups=g.pickups.filter(q=>q.life>0);
for(let x of g.particles){x.x+=x.vx*dt;x.y+=x.vy*dt;x.vx*=.94;x.vy*=.94;x.life-=dt}g.particles=g.particles.filter(x=>x.life>0);updateUI()}
function updateUI(){let g=game,p=g.player;if(!g)return;ui.score.textContent=String(g.score).padStart(6,'0');ui.wave.textContent=String(g.wave).padStart(2,'0');ui.best.textContent=String(Math.max(Number(localStorage.neonBest||0),g.score)).padStart(6,'0');ui.healthBar.style.width=clamp(p.hp,0,100)+'%';ui.healthNum.textContent=Math.ceil(p.hp);ui.energyBar.style.width=p.energy+'%';ui.ammoNum.textContent=p.weapon?'OVR':'∞';ui.weaponName.textContent=p.weapon?'TRI-SHOT OVERDRIVE':'PULSE RIFLE';ui.combo.textContent='×'+p.combo+' COMBO'}
function draw(){let g=game,p=g.player, shake=g.shake||0, sx=rand(-shake,shake),sy=rand(-shake,shake);c.clearRect(0,0,W,H);c.save();c.translate(sx,sy);c.fillStyle='#081326';c.fillRect(-30,-30,W+60,H+60);c.strokeStyle='rgba(63,176,239,.12)';c.lineWidth=1;let grid=48;for(let x=-grid+(g.time*13%grid);x<W+grid;x+=grid){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke()}for(let y=-grid+(g.time*13%grid);y<H+grid;y+=grid){c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke()}
for(let s of g.stars){c.fillStyle=`rgba(111,225,255,${.15+s.z*.35})`;c.fillRect(s.x,s.y,s.z*2,s.z*2)}
for(let q of g.pickups){let col=q.type==='heal'?'#53ff9f':'#ff5b9a';c.save();c.translate(q.x,q.y);c.rotate(g.time*3);c.shadowBlur=18;c.shadowColor=col;c.strokeStyle=col;c.lineWidth=2;c.strokeRect(-7,-7,14,14);c.restore()}
for(let b of g.bullets){c.shadowBlur=16;c.shadowColor=b.color;c.fillStyle=b.color;c.beginPath();c.arc(b.x,b.y,b.r,0,7);c.fill()}c.shadowBlur=0;
for(let e of g.enemies){c.save();c.translate(e.x,e.y);c.rotate(e.angle);let col=e.elite?'#ffbd5b':'#ff3b81';c.shadowColor=col;c.shadowBlur=15;c.fillStyle=e.hit>0?'#fff':col;c.beginPath();c.moveTo(e.r+4,0);c.lineTo(-e.r,e.r*.78);c.lineTo(-e.r,-e.r*.78);c.closePath();c.fill();c.fillStyle='#150916';c.beginPath();c.arc(3,0,e.r*.28,0,7);c.fill();c.restore();if(e.elite||e.hp<e.max){c.fillStyle='rgba(0,0,0,.5)';c.fillRect(e.x-e.r,e.y-e.r-11,e.r*2,3);c.fillStyle=col;c.fillRect(e.x-e.r,e.y-e.r-11,e.r*2*e.hp/e.max,3)}}
for(let x of g.particles){c.globalAlpha=x.life/x.max;c.fillStyle=x.color;c.fillRect(x.x-x.size/2,x.y-x.size/2,x.size,x.size)}c.globalAlpha=1;
c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.shadowBlur=22;c.shadowColor=p.inv>0?'#fff':'#47f4ff';c.fillStyle=p.inv>0&&Math.floor(g.time*15)%2?'#fff':'#47f4ff';c.beginPath();c.moveTo(23,0);c.lineTo(-14,13);c.lineTo(-8,0);c.lineTo(-14,-13);c.closePath();c.fill();c.fillStyle='#06101e';c.fillRect(1,-4,22,8);c.restore();c.restore();
// reticle
c.strokeStyle='rgba(220,252,255,.85)';c.lineWidth=1;c.beginPath();c.arc(mouse.x,mouse.y,10,0,7);c.moveTo(mouse.x-15,mouse.y);c.lineTo(mouse.x-7,mouse.y);c.moveTo(mouse.x+7,mouse.y);c.lineTo(mouse.x+15,mouse.y);c.stroke()}
function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;if(game.active&&!game.paused)update(dt);draw();raf=requestAnimationFrame(loop)}
function end(){game.active=false;localStorage.neonBest=Math.max(Number(localStorage.neonBest||0),game.score);ui.finalScore.textContent=String(game.score).padStart(6,'0');ui.finalWave.textContent=String(game.wave).padStart(2,'0');screens.over.classList.remove('hidden')}
function togglePause(){if(!game||!game.active)return;game.paused=!game.paused;screens.pause.classList.toggle('hidden',!game.paused)}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){e.preventDefault();if(game?.active&&game.player.dash<=0&&game.player.energy>=25){let p=game.player;p.energy-=25;p.dash=.14;p.inv=.2;burst(p.x,p.y,'#47f4ff',15)}}if(e.code==='KeyP'||e.code==='Escape')togglePause()});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('pointermove',e=>{let r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top});canvas.addEventListener('pointerdown',e=>{mouse.down=true;canvas.setPointerCapture?.(e.pointerId)});addEventListener('pointerup',()=>mouse.down=false);document.getElementById('startButton').onclick=start;document.getElementById('restartButton').onclick=start;document.getElementById('resumeButton').onclick=togglePause;
// attract mode
game={active:false,paused:false,time:0,shake:0,stars:Array.from({length:115},()=>({x:Math.random()*W,y:Math.random()*H,z:rand(.2,1)})),enemies:[],bullets:[],particles:[],pickups:[],player:{x:W/2,y:H/2,angle:0}};raf=requestAnimationFrame(loop);

